=== andreiolaru-ro/AmIciTy-Mi/test/KCASchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- no namespace with elementFormDefault = qualified -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/scenarioSchema"
	xmlns:t="http://www.example.org/scenarioSchema" elementFormDefault="qualified">


	<!-- COMPLEX TYPE -->
	<complexType name="agentLocation">
		<sequence>
			<element name="first" type="decimal" />
			<element name="last" type="decimal" />
			<element name="count" type="nonNegativeInteger" />
		</sequence>
	</complexType>

	<group name="parameters">
		<sequence>
			<element name="first" type="decimal" minOccurs="0" maxOccurs="1" />
			<element name="last" type="decimal" minOccurs="0" maxOccurs="1" />
			<element name="count" type="nonNegativeInteger" minOccurs="0"
				maxOccurs="1" />
			<element name="mean" type="decimal" minOccurs="0" maxOccurs="1" />
			<element name="dev" type="decimal" minOccurs="0" maxOccurs="1" />
			<element name="min" type="decimal" minOccurs="0" maxOccurs="1" />
			<element name="max" type="decimal" minOccurs="0" maxOccurs="1" />
			<element name="list" type="string" minOccurs="0" maxOccurs="1" />
			<element name="select" type="nonNegativeInteger" minOccurs="0"
				maxOccurs="1" />
			<element name="step" type="decimal" minOccurs="0" maxOccurs="1" />
			<element name="foreach" type="string" minOccurs="0"
				maxOccurs="unbounded" />
		</sequence>
	</group>

	<complexType name="eventStringValue">
		<choice>
			<group ref="t:parameters" />
			<element name="value" type="string" />
		</choice>
	</complexType>

	<complexType name="eventIntegerValue">
		<choice>
			<group ref="t:parameters" />
			<element name="value" type="integer" />
		</choice>
	</complexType>

	<complexType name="eventDecimalValue">
		<choice>
			<group ref="t:parameters" />
			<element name="value" type="decimal" />
		</choice>
	</complexType>

	<complexType name="eventBoundedValue">
		<choice>
			<group ref="t:parameters" />
			<element name="value">
				<simpleType>
					<restriction base="decimal">
						<minInclusive value="0" />
						<maxInclusive value="1" />
					</restriction>
				</simpleType>
			</element>
		</choice>
	</complexType>

	<!-- XML STRUCTURE -->
	<element name="scenario">
		<complexType>
			<sequence>
				<element name="map">
					<complexType>
						<sequence>
							<element name="characteristic">
								<complexType>
									<sequence>
										<element name="coordinates">
											<complexType>
												<sequence>
													<element name="x" type="decimal" />
													<element name="y" type="decimal" />
												</sequence>
											</complexType>
										</element>
										<element name="size">
											<complexType>
												<sequence>
													<element name="width" type="decimal" />
													<element name="height" type="decimal" />
												</sequence>
											</complexType>
										</element>
									</sequence>
								</complexType>
							</element>
							<element name="agent">
								<complexType>
									<sequence>
										<!-- <element name="type" type="string" maxOccurs="1" -->
										<!-- minOccurs="0" /> -->
										<element name="location">
											<complexType>
												<sequence>
													<element name="x" type="t:agentLocation" />
													<element name="y" type="t:agentLocation" />
												</sequence>
											</complexType>
										</element>
									</sequence>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>

				<element name="timeline">
					<complexType>
						<sequence>
							<element name="event" minOccurs="0" maxOccurs="unbounded">
								<complexType>
									<sequence>
										<element name="type">
											<simpleType>
												<restriction base="string">
													<enumeration value="inject" />
													<enumeration value="request" />
													<enumeration value="snapshot" />
												</restriction>
											</simpleType>
										</element>
										<element name="pressure" type="t:eventBoundedValue" />
										<element name="persistence" type="t:eventBoundedValue" />
										<element name="domain">
											<complexType>
												<sequence>
													<element name="a" type="t:eventBoundedValue" />
													<element name="b" type="t:eventBoundedValue" />
													<element name="c" type="t:eventBoundedValue" />
												</sequence>
											</complexType>
										</element>
										<element name="location">
											<complexType>
												<sequence>
													<element name="x" type="t:eventIntegerValue" />
													<element name="y" type="t:eventIntegerValue" />
												</sequence>
											</complexType>
										</element>
										<element name="time" type="t:eventIntegerValue" />
									</sequence>
								</complexType>
							</element>
						</sequence>
						<attribute name="duration" type="positiveInteger" use="required" />
					</complexType>
				</element>
			</sequence>

			<attribute name="seed" type="integer" use="optional" />
		</complexType>
	</element>


</schema>

=== andreiolaru-ro/AmIciTy-Mi/scenarios/kca_test3r.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (C) 2013 Andrei Olaru. See the AUTHORS file for more information.
  
  This file is part of AmIciTy-Mi.
  
  AmIciTy-Mi is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
  
  AmIciTy-Mi is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License along with AmIciTy-Mi.  If not, see <http://www.gnu.org/licenses/>.
-->
<scen:scenario seed="-56552949266271195"
	xmlns:pr="http://www.example.org/parameterSchema" xmlns:scen="http://www.example.org/scenarioSchema"
	xmlns:ma="http://www.example.org/mapSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:sel="http://www.example.org/selectionSchema"
	xsi:schemaLocation="http://www.example.org/scenarioSchema ../schemas/agent/kcaSchema.xsd ">

	<scen:map>
		<ma:features>
			<ma:coordinates>
				<ma:x>0</ma:x>
				<ma:y>0</ma:y>
			</ma:coordinates>
			<ma:size>
				<ma:width>31</ma:width>
				<ma:height>31</ma:height>
			</ma:size>
		</ma:features>
		<ma:agent>
			<ma:location>
				<ma:x>
					<pr:first>0</pr:first>
					<pr:last>30</pr:last>
					<pr:count>31</pr:count>
				</ma:x>
				<ma:y>
					<pr:first>0</pr:first>
					<pr:last>30</pr:last>
					<pr:count>31</pr:count>
				</ma:y>
			</ma:location>
		</ma:agent>
	</scen:map>

	<scen:timeline duration="1000">
		<scen:event>
			<scen:type>inject</scen:type>
			<scen:pressure>
				<pr:value>0.1</pr:value>
			</scen:pressure>
			<scen:persistence>
				<pr:value>0.05</pr:value>
			</scen:persistence>
			<scen:domain>
				<scen:a>
					<pr:value>1</pr:value>
				</scen:a>
				<scen:b>
					<pr:value>0</pr:value>
				</scen:b>
				<scen:c>
					<pr:value>0</pr:value>
				</scen:c>
			</scen:domain>
			<scen:location>
				<scen:x>
					<pr:dev>2</pr:dev>
					<pr:min>0</pr:min>
					<pr:max>30</pr:max>
					<pr:foreach>time</pr:foreach>
				</scen:x>
				<scen:y>
					<pr:dev>2</pr:dev>
					<pr:min>0</pr:min>
					<pr:max>30</pr:max>
					<pr:select>1</pr:select>
					<pr:foreach>time</pr:foreach>
					<pr:foreach>location/x</pr:foreach>
				</scen:y>
			</scen:location>
			<scen:time>
				<pr:min>0</pr:min>
				<pr:max>150</pr:max>
				<pr:select>15</pr:select>
			</scen:time>
		</scen:event>

		<scen:event>
			<scen:type>inject</scen:type>
			<scen:pressure>
				<pr:value>0.1</pr:value>
			</scen:pressure>
			<scen:persistence>
				<pr:value>0.05</pr:value>
			</scen:persistence>
			<scen:domain>
				<scen:a>
					<pr:value>0</pr:value>
				</scen:a>
				<scen:b>
					<pr:value>0</pr:value>
				</scen:b>
				<scen:c>
					<pr:value>1</pr:value>
				</scen:c>
			</scen:domain>
			<scen:location>
				<scen:x>
					<pr:dev>2</pr:dev>
					<pr:min>0</pr:min>
					<pr:max>30</pr:max>
					<pr:foreach>time</pr:foreach>
				</scen:x>
				<scen:y>
					<pr:dev>2</pr:dev>
					<pr:min>0</pr:min>
					<pr:max>30</pr:max>
					<pr:select>1</pr:select>
					<pr:foreach>time</pr:foreach>
					<pr:foreach>location/x</pr:foreach>
				</scen:y>
			</scen:location>
			<scen:time>
				<pr:dev>2</pr:dev>
				<pr:min>0</pr:min>
				<pr:max>150</pr:max>
				<pr:select>15</pr:select>
			</scen:time>
		</scen:event>
		<scen:event>
			<scen:type>inject</scen:type>
			<scen:pressure>
				<pr:value>0.1</pr:value>
			</scen:pressure>
			<scen:persistence>
				<pr:value>0.05</pr:value>
			</scen:persistence>
			<scen:domain>
				<scen:a>
					<pr:value>0</pr:value>
				</scen:a>
				<scen:b>
					<pr:value>1</pr:value>
				</scen:b>
				<scen:c>
					<pr:value>0</pr:value>
				</scen:c>
			</scen:domain>
			<scen:location>
				<scen:x>
					<pr:dev>2</pr:dev>
					<pr:min>0</pr:min>
					<pr:max>30</pr:max>
					<pr:foreach>time</pr:foreach>
				</scen:x>
				<scen:y>
					<pr:dev>2</pr:dev>
					<pr:min>0</pr:min>
					<pr:max>30</pr:max>
					<pr:select>1</pr:select>
					<pr:foreach>time</pr:foreach>
					<pr:foreach>location/x</pr:foreach>
				</scen:y>
			</scen:location>
			<scen:time>
				<pr:dev>2</pr:dev>
				<pr:min>0</pr:min>
				<pr:max>150</pr:max>
				<pr:select>15</pr:select>
			</scen:time>
		</scen:event>

		<scen:event>
			<scen:type>inject</scen:type>
			<scen:pressure>
				<pr:value>0.1</pr:value>
			</scen:pressure>
			<scen:persistence>
				<pr:value>0.02</pr:value>
			</scen:persistence>
			<scen:domain>
				<scen:a>
					<pr:value>0</pr:value>
				</scen:a>
				<scen:b>
					<pr:value>1</pr:value>
				</scen:b>
				<scen:c>
					<pr:value>0.1</pr:value>
				</scen:c>
			</scen:domain>
			<scen:location>
				<scen:x>
					<pr:value>5</pr:value>
				</scen:x>
				<scen:y>
					<pr:value>5</pr:value>
				</scen:y>
			</scen:location>
			<scen:time>
				<pr:value>70</pr:value>
			</scen:time>
		</scen:event>
		
		
		<scen:event>
			<scen:type>inject</scen:type>
			<scen:pressure>
				<pr:value>0.5</pr:value>
			</scen:pressure>
			<scen:persistence>
				<pr:value>0.95</pr:value>
			</scen:persistence>
			<scen:domain>
				<scen:a>
					<pr:value>1</pr:value>
				</scen:a>
				<scen:b>
					<pr:value>0.1</pr:value>
				</scen:b>
				<scen:c>
					<pr:value>0</pr:value>
				</scen:c>
			</scen:domain>
			<scen:location>
				<scen:x>
					<pr:min>10</pr:min>
					<pr:max>20</pr:max>
					<pr:select>1</pr:select>
					<pr:foreach>time</pr:foreach>
				</scen:x>
				<scen:y>
					<pr:min>10</pr:min>
					<pr:max>20</pr:max>
					<pr:select>1</pr:select>
					<pr:foreach>time</pr:foreach>
					<pr:foreach>location/x</pr:foreach>
				</scen:y>
			</scen:location>
			<scen:time>
				<pr:value>130</pr:value>
			</scen:time>
		</scen:event>

		<scen:event>
			<scen:type>inject</scen:type>
			<scen:pressure>
				<pr:value>0.5</pr:value>
			</scen:pressure>
			<scen:persistence>
				<pr:value>0.95</pr:value>
			</scen:persistence>
			<scen:domain>
				<scen:a>
					<pr:value>0</pr:value>
				</scen:a>
				<scen:b>
					<pr:value>1</pr:value>
				</scen:b>
				<scen:c>
					<pr:value>0.1</pr:value>
				</scen:c>
			</scen:domain>
			<scen:location>
				<scen:x>
					<pr:min>10</pr:min>
					<pr:max>20</pr:max>
					<pr:select>1</pr:select>
					<pr:foreach>time</pr:foreach>
				</scen:x>
				<scen:y>
					<pr:min>10</pr:min>
					<pr:max>20</pr:max>
					<pr:select>1</pr:select>
					<pr:foreach>time</pr:foreach>
					<pr:foreach>location/x</pr:foreach>
				</scen:y>
			</scen:location>
			<scen:time>
				<pr:value>130</pr:value>
			</scen:time>
		</scen:event>

		<scen:event>
			<scen:type>inject</scen:type>
			<scen:pressure>
				<pr:value>0.5</pr:value>
			</scen:pressure>
			<scen:persistence>
				<pr:value>0.95</pr:value>
			</scen:persistence>
			<scen:domain>
				<scen:a>
					<pr:value>0.1</pr:value>
				</scen:a>
				<scen:b>
					<pr:value>0</pr:value>
				</scen:b>
				<scen:c>
					<pr:value>1</pr:value>
				</scen:c>
			</scen:domain>
			<scen:location>
				<scen:x>
					<pr:min>10</pr:min>
					<pr:max>20</pr:max>
					<pr:select>1</pr:select>
					<pr:foreach>time</pr:foreach>
				</scen:x>
				<scen:y>
					<pr:min>10</pr:min>
					<pr:max>20</pr:max>
					<pr:select>1</pr:select>
					<pr:foreach>time</pr:foreach>
					<pr:foreach>location/x</pr:foreach>
				</scen:y>
			</scen:location>
			<scen:time>
				<pr:value>130</pr:value>
			</scen:time>
		</scen:event>

		<scen:event>
			<scen:type>inject</scen:type>
			<scen:pressure>
				<pr:value>0.9</pr:value>
			</scen:pressure>
			<scen:persistence>
				<pr:value>0.5</pr:value>
			</scen:persistence>
			<scen:domain>
				<scen:a>
					<pr:value>0.3</pr:value>
				</scen:a>
				<scen:b>
					<pr:value>0.3</pr:value>
				</scen:b>
				<scen:c>
					<pr:value>0.3</pr:value>
				</scen:c>
			</scen:domain>
			<scen:location>
				<scen:x>
					<pr:value>5</pr:value>
				</scen:x>
				<scen:y>
					<pr:value>5</pr:value>
				</scen:y>
			</scen:location>
			<scen:time>
				<pr:value>200</pr:value>
			</scen:time>
		</scen:event>
	</scen:timeline>
</scen:scenario>
