=== andreiolaru-ro/AmIciTy-Mi/playground/xml/scenarioSchema2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/scenarioSchema"
	xmlns:tns="http://www.example.org/scenarioSchema" elementFormDefault="qualified">
	<element name="scenario">
		<complexType>
			<sequence>
				<element name="jadeConfig" maxOccurs="1" minOccurs="0">
					<complexType>
						<attribute name="isMain" type="boolean" use="optional"
							default="false" />
						<attribute name="IPaddress" type="string" use="optional" />
						<attribute name="port" type="positiveInteger" use="optional" />
						<attribute name="platformID" type="positiveInteger" use="optional" />
						<attribute name="mainContainerName" type="string" use="optional" />
					</complexType>
				</element>
				<element name="adfPath" type="string" minOccurs="0"
					maxOccurs="unbounded" />
				<element name="agentPackage" type="string" minOccurs="0"
					maxOccurs="unbounded" />
				<element name="initial" maxOccurs="1" minOccurs="0">
					<complexType>
						<sequence>
							<element name="container" minOccurs="1" maxOccurs="unbounded">
								<complexType>
									<sequence>
										<element name="agent" maxOccurs="unbounded" minOccurs="0">
											<complexType>
												<sequence>
													<element name="parameter" minOccurs="0" maxOccurs="unbounded">
														<complexType>
															<attribute name="name" type="string" use="required" />
															<attribute name="value" type="string" use="required" />
														</complexType>
													</element>
												</sequence>
											</complexType>
										</element>
									</sequence>
									<attribute name="name" type="string" use="required" />
									<attribute name="create" type="boolean" use="optional"
										default="true" />
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
				<element name="timeline" maxOccurs="1" minOccurs="0">
					<complexType>
						<sequence>
							<element name="event" minOccurs="1" maxOccurs="unbounded">
								<complexType>
									<sequence>
										<element name="CLAIMMessage" maxOccurs="unbounded"
											minOccurs="0">
											<complexType>
												<sequence>
													<element name="to" type="string" minOccurs="1"
														maxOccurs="unbounded" />
													<element name="protocol" type="string" minOccurs="0"
														maxOccurs="1" />
													<element name="content" type="string" minOccurs="0"
														maxOccurs="1" />
												</sequence>
											</complexType>
										</element>
									</sequence>
									<attribute name="time" type="positiveInteger" use="required" />
								</complexType>
							</element>
						</sequence>
						<attribute name="duration" type="positiveInteger" use="optional">
						</attribute>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>

</schema>

=== andreiolaru-ro/AmIciTy-Mi/playground/xml/scenario.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (C) 2013 Andrei Olaru. See the AUTHORS file for more information.
  
  This file is part of AmIciTy-Mi.
  
  AmIciTy-Mi is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
  
  AmIciTy-Mi is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License along with AmIciTy-Mi.  If not, see <http://www.gnu.org/licenses/>.
-->
<scen:scenario 
	xmlns:pr="http://www.example.org/parameterSchema"
	xmlns:kb="http://www.example.org/kbSchema" 
	xmlns:scen="http://www.example.org/scenarioSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/scenarioSchema ./scenarioSchema2.xsd ">

	<scen:jadeConfig mainContainerName="ContainerRoot" />
	<scen:adfPath>scenario/examples/simpleScenarioC</scen:adfPath>
	<scen:agentPackage>agent_packages.example</scen:agentPackage>

	<scen:initial>
		<scen:container name="ContainerRoot">
			<scen:agent>
				<scen:parameter name="loader" value="adf2" />
				<scen:parameter name="class" value="UnitaryAgent" />
				<scen:parameter name="name" value="root" />
				<scen:parameter name="java-code" value="StringFunctions" />
			</scen:agent>
			<scen:agent>
				<scen:parameter name="loader" value="adf2" />
				<scen:parameter name="class" value="UnitaryAgent" />
				<scen:parameter name="name" value="master" />
				<scen:parameter name="parent" value="root" />
			</scen:agent>
		</scen:container>

		<scen:container name="ContainerRoaming">
			<scen:agent>
				<scen:parameter name="loader" value="adf2" />
				<scen:parameter name="class" value="UnitaryAgent" />
				<scen:parameter name="name" value="roaming" />
				<scen:parameter name="parent" value="root" />
				<scen:parameter name="java-code" value="StringFunctions" />
			</scen:agent>
			<scen:agent>
				<scen:parameter name="loader" value="adf2" />
				<scen:parameter name="class" value="UnitaryAgent" />
				<scen:parameter name="name" value="slave" />
				<scen:parameter name="parent" value="roaming" />
				<scen:parameter name="java-code" value="StringFunctions" />
				<scen:parameter name="knowledge" value="masterAgent -is> master" />
			</scen:agent>
		</scen:container>
	</scen:initial>
	<scen:timeline>
		<scen:event time="2000">
			<scen:CLAIMMessage>
				<scen:to>root</scen:to>
				<scen:content>( struct message go-gather-root roaming )</scen:content>
			</scen:CLAIMMessage>
		</scen:event>
	</scen:timeline>
</scen:scenario>
